version: '3.9'

services:

  # Uncomment the following section if you plan to use the djangoapp service
  # djangoapp:
  #   container_name: djangoapp
  #   build: .
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - PG_USER=athish
  #     - PG_PASSWORD=Athish@123
  #     - PG_DB=myproject
  #     - PG_HOST=db
  #     - PG_PORT=5432
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dryz
    ports:
      - "5433:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
  
volumes:
  static: {}