version: '3.9'

services:

 

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dryz
    ports:
      - "5433:5432"
#     networks:
#       - mynetwork
# networks:
#   mynetwork:
#     driver: bridge
  
